# Generated by Django 3.2.4 on 2023-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('spotify_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='spotify_id')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spotify',
            },
        ),
        migrations.CreateModel(
            name='Vimeo',
            fields=[
                ('vimeo_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='vimeo_id')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vimeo',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('youtube_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='youtube_id')),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'youtube',
            },
        ),
    ]
