# Generated by Django 3.2.4 on 2022-03-27 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='genero_id')),
                ('genero_descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Genero',
            },
        ),
        migrations.CreateModel(
            name='Genero_musical',
            fields=[
                ('genero_musical_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='genero_musical_id')),
                ('genero_musical_descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'genero_musical',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('habilidad_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='habilidad_id')),
                ('habilidad_descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usuario_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='usuario_id')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('acerca_de_mi', models.CharField(max_length=250)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero', verbose_name='genero_id')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario_habilidad',
            fields=[
                ('usuario_habilidad_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Usuario_habilidad_id')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habilidad', verbose_name='habilidad_id')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios', verbose_name='usuario_id')),
            ],
            options={
                'db_table': 'Usuario_habilidad',
            },
        ),
        migrations.CreateModel(
            name='Usuario_genero_musical',
            fields=[
                ('usuario_genero_musical_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='usuario_genero_musical_id')),
                ('genero_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero_musical', verbose_name='genero_musical_id')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios', verbose_name='usuario_id')),
            ],
            options={
                'db_table': 'usuario_genero_musical',
            },
        ),
        migrations.CreateModel(
            name='Usuario_artista',
            fields=[
                ('usuario_artista_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='usuario_artista_id')),
                ('artista_id', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios', verbose_name='usuario_id')),
            ],
            options={
                'db_table': 'usuario_artista',
            },
        ),
    ]
