# Generated by Django 3.2.4 on 2022-08-15 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='format_id')),
                ('format_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Format',
            },
        ),
        migrations.CreateModel(
            name='Multimedia_status',
            fields=[
                ('multimedia_status_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='multimedia_status_id')),
                ('multimedia_desc', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Multimedia_status',
            },
        ),
        migrations.AlterField(
            model_name='multimedia_type',
            name='multimedia_type_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='multimedia_type_id'),
        ),
        migrations.AlterModelTable(
            name='multimedia_type',
            table='Multimedia_type',
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('multimedia_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='multimedia_id')),
                ('url', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.format', verbose_name='format_id')),
                ('multimedia_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.multimedia_status', verbose_name='multimedia_status_id')),
                ('multimedia_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.multimedia_type', verbose_name='multimedia_type_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'Multimedia',
            },
        ),
    ]
