# Generated by Django 3.2.4 on 2022-02-27 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='genero_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero', verbose_name='genero_id'),
        ),
    ]
