# Generated by Django 3.2.4 on 2022-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('plataforma_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='plaforma_id')),
                ('plataforma_descripcion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'plataforma',
            },
        ),
        migrations.RemoveField(
            model_name='genero_musical',
            name='genero_musical_descripcion',
        ),
    ]
