# Generated by Django 3.2.4 on 2023-01-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='caption',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
