# Generated by Django 3.2.4 on 2022-02-27 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarios_genero_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='genero_id',
            new_name='genero',
        ),
    ]
