# Generated by Django 3.2.4 on 2022-02-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarios_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
