# Generated by Django 3.2.4 on 2022-03-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220326_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma_usuario',
            fields=[
                ('plataforma_usuario_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='plaforma_id')),
                ('plataforma_descripcion', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plataforma', verbose_name='plataforma_id')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios', verbose_name='usuario_id')),
            ],
            options={
                'db_table': 'plataforma_usuario',
            },
        ),
    ]
