# Generated by Django 3.2.4 on 2022-03-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_plataforma_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plataforma_usuario',
            new_name='Usuario_plataforma',
        ),
        migrations.AlterModelTable(
            name='usuario_plataforma',
            table='Usuario_plataforma',
        ),
    ]
