# Generated by Django 3.2.4 on 2022-02-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_genero_id_usuarios_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_artista',
            fields=[
                ('usuario_artista_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='usuario_artista_id')),
                ('artista_id', models.CharField(max_length=200)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios', verbose_name='usuario_id')),
            ],
            options={
                'db_table': 'usuario_artista',
            },
        ),
    ]
