# Generated by Django 3.2.4 on 2022-03-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220326_2153'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario_plataforma',
            table='usuario_plataforma',
        ),
    ]
