# Generated by Django 3.2.4 on 2022-08-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_1',
            new_name='image',
        ),
    ]
