# Generated by Django 3.2.4 on 2022-03-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_plataforma_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_plataforma',
            name='plataforma_descripcion',
        ),
    ]
