# Generated by Django 3.2.4 on 2022-02-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_artista_artista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion_usuario',
            field=models.DateField(auto_now_add=True),
        ),
    ]
