# Generated by Django 3.2.4 on 2022-04-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_usuario_plataforma_plataforma_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vimeo',
            fields=[
                ('vimeo_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='plaforma_id')),
                ('client_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vimeo',
            },
        ),
    ]
