# Generated by Django 3.2.4 on 2022-02-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usuarios_fecha_creacion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='fecha_creacion_usuario',
            new_name='fecha_creacion',
        ),
    ]
