# Generated by Django 3.2.4 on 2022-04-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vimeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vimeo',
            name='client_secret',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
