# Generated by Django 3.2.4 on 2022-04-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_vimeo_client_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('spotify_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='plaforma_id')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spotify',
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('youtube_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='plaforma_id')),
                ('key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'youtube',
            },
        ),
    ]
