# Generated by Django 3.2.4 on 2022-07-08 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_spotify_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='skill_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='skill_1_id'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='skill_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='skill_2_id'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='skill_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='skill_3_id'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='skill_4',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='skill_4_id'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='skill_5',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='skill_5_id'),
        ),
    ]
