# Generated by Django 3.2.4 on 2022-07-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220708_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='skill_1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.habilidad', verbose_name='habilidad_id'),
        ),
    ]
