# Generated by Django 3.2.4 on 2023-01-27 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('inbox_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='inbox_id')),
                ('latest_message', models.CharField(max_length=1000, null=True)),
                ('unseen_messages', models.IntegerField(default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('inbox_user_to_sender', models.CharField(max_length=1000, null=True)),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender_id')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('message_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='chat_id')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('inbox_user_to_sender', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender_id')),
            ],
        ),
    ]
