# Generated by Django 3.2.4 on 2022-10-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('inbox_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='inbox_id')),
            ],
        ),
    ]
