# Generated by Django 3.2.4 on 2022-10-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_inbox_inbox_user_to_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
