# Generated by Django 3.2.4 on 2022-10-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_inbox_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='latest_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
