# Generated by Django 4.1.4 on 2023-01-05 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='nationality_id')),
                ('nationality_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Nationalities',
            },
        ),
        migrations.CreateModel(
            name='User_Nationality',
            fields=[
                ('user_nationality_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_nationality_id')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.nationality', verbose_name='nationality_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='nationality_id')),
            ],
            options={
                'db_table': 'User_Nationalities',
            },
        ),
    ]
