# Generated by Django 3.2.4 on 2022-07-15 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='skill_id')),
                ('skill_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Skills',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='user_id'),
        ),
        migrations.CreateModel(
            name='User_Skills',
            fields=[
                ('user_skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_skill_id')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.skills', verbose_name='skill_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Skills',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skill_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_1', to='authentication.skills', verbose_name='skill_1_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_2', to='authentication.skills', verbose_name='skill_2_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_3', to='authentication.skills', verbose_name='skill_3_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_4', to='authentication.skills', verbose_name='skill_4_id'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_5', to='authentication.skills', verbose_name='skill_5_id'),
        ),
    ]
