# Generated by Django 3.2.4 on 2022-08-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220715_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='genre_id')),
                ('genre_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_5',
        ),
        migrations.CreateModel(
            name='User_Genres',
            fields=[
                ('user_genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_genre_id')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genres', verbose_name='genre_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Genres',
            },
        ),
    ]
