# Generated by Django 3.2.4 on 2022-08-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220815_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
