# Generated by Django 3.2.4 on 2022-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_artists',
            name='artist',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
