# Generated by Django 3.2.4 on 2022-12-20 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_artists_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Youtube',
            fields=[
                ('user_youtube_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_artist_id')),
                ('videoID', models.CharField(max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Youtube',
            },
        ),
    ]
