# Generated by Django 3.2.4 on 2022-12-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_artists',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_youtube',
            name='videoID',
            field=models.CharField(max_length=200),
        ),
    ]
