# Generated by Django 3.2.4 on 2023-02-04 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_likes',
            name='userOne',
        ),
        migrations.AddField(
            model_name='user_likes',
            name='userLiking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userLiking', to=settings.AUTH_USER_MODEL, verbose_name='userLiking'),
        ),
    ]
