# Generated by Django 4.1.4 on 2023-01-11 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preferences_Skills',
            fields=[
                ('preference_skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_skill_id')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.skills', verbose_name='skill_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Skills',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Genres',
            fields=[
                ('preference_genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_genre_id')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genres', verbose_name='genre_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Genres',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Genders',
            fields=[
                ('preference_gender_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_gender_id')),
                ('genders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genders', verbose_name='gender_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Genders',
            },
        ),
    ]
