# Generated by Django 3.2.4 on 2023-02-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preferences_Globally',
            fields=[
                ('preference_globally_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_globally_id')),
                ('search_globally', models.BooleanField(default=True, verbose_name='search_globally')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Globally',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Distance',
            fields=[
                ('preference_distance_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_distance_id')),
                ('distance_low', models.IntegerField(verbose_name='distance_low')),
                ('distance_high', models.IntegerField(verbose_name='distance_high')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Distance',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Age',
            fields=[
                ('preference_age_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='age_id')),
                ('age_low', models.IntegerField(verbose_name='age_low')),
                ('age_high', models.IntegerField(verbose_name='age_high')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Age',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Skills',
            fields=[
                ('user_skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_skill_id')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.skills', verbose_name='skill_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preference_Skills',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Genres',
            fields=[
                ('user_preference_genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_genre_id')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genres', verbose_name='genre_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preference_Genres',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Genders',
            fields=[
                ('preference_user_gender_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_gender_id')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genders', verbose_name='gender_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preference_Genders',
            },
        ),
    ]
