# Generated by Django 4.1.4 on 2023-01-12 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference_Genders',
            fields=[
                ('preference_gender_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='preference_gender_id')),
                ('preference_gender_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Preference_Genders',
            },
        ),
        migrations.CreateModel(
            name='Preference_Genres',
            fields=[
                ('preference_genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='preference_genre_id')),
                ('preference_genre_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Preference_Genres',
            },
        ),
        migrations.CreateModel(
            name='Preference_Skills',
            fields=[
                ('preference_skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='preference_skill_id')),
                ('preference_skill_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'Preference_Skills',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Genders',
            fields=[
                ('preference_user_gender_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='preference_user_gender_id')),
                ('preference_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.preference_genders', verbose_name='preference_gender_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'Preference_User_Genders',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Genres',
            fields=[
                ('user_preference_genre_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_preference_genre_id')),
                ('preference_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.preference_genres', verbose_name='preference_genre_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preference_Genres',
            },
        ),
        migrations.CreateModel(
            name='User_Preference_Skills',
            fields=[
                ('user_skill_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_skill_id')),
                ('preference_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.preference_skills', verbose_name='preference_skill_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preference_Skills',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Age',
            fields=[
                ('preference_age_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_age_id')),
                ('age_low', models.IntegerField(verbose_name='age_low')),
                ('age_high', models.IntegerField(verbose_name='age_high')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Age',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Distance',
            fields=[
                ('preference_distance_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_distance_id')),
                ('distance_low', models.IntegerField(verbose_name='distance_low')),
                ('distance_high', models.IntegerField(verbose_name='distance_high')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Distance',
            },
        ),
        migrations.CreateModel(
            name='User_Preferences_Globally',
            fields=[
                ('preference_globally_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='user_globally_id')),
                ('isGlobal', models.BooleanField(verbose_name='is_global')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'db_table': 'User_Preferences_Globally',
            },
        ),
        migrations.RemoveField(
            model_name='user_preferences_genres',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='user_preferences_genres',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_preferences_skills',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user_preferences_skills',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Preferences_Genders',
        ),
        migrations.DeleteModel(
            name='User_Preferences_Genres',
        ),
        migrations.DeleteModel(
            name='User_Preferences_Skills',
        ),
    ]
