# Generated by Django 4.1.4 on 2023-01-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('preferences', '0004_alter_user_preference_genders_preference_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_preference_genders',
            name='preference_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genders', verbose_name='preference_gender_id'),
        ),
        migrations.AlterField(
            model_name='user_preference_genres',
            name='preference_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.genres', verbose_name='preference_genre_id'),
        ),
    ]
