# Generated by Django 4.1.4 on 2023-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0006_alter_user_preference_genders_preference_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_preference_genders',
            old_name='preference_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user_preference_genres',
            old_name='preference_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='user_preference_skills',
            old_name='preference_skill',
            new_name='skill',
        ),
    ]
