# Generated by Django 4.1.4 on 2023-01-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0007_rename_preference_gender_user_preference_genders_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_preference_genders',
            table='User_Preference_Genders',
        ),
    ]
