# Generated by Django 4.1.4 on 2023-01-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0008_alter_user_preference_genders_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_preferences_globally',
            name='isGlobal',
        ),
        migrations.AddField(
            model_name='user_preferences_globally',
            name='search_globally',
            field=models.BooleanField(default=True, verbose_name='search_globally'),
        ),
    ]
